# Generated by Django 3.2.9 on 2022-03-14 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformanceChecking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('frecuency_time', models.IntegerField()),
                ('frecuency', models.CharField(max_length=7)),
                ('os_user', models.CharField(max_length=30)),
                ('user_ip', models.GenericIPAddressField()),
                ('log_file', models.CharField(max_length=300)),
                ('port_number', models.IntegerField()),
                ('ssh_pub_key', models.CharField(max_length=2000)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dataset')),
            ],
        ),
    ]
