# Generated by Django 3.2.9 on 2022-03-18 07:45

from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import main.enums


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0015_edit_solarschedule_events_choices'),
        ('main', '0002_conformancechecking'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformancechecking',
            name='status',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Active', 'Active'), ('Disabled', 'Disabled')], default=main.enums.SetupStatus['active'], enum_class=main.enums.SetupStatus, max_length=8),
        ),
        migrations.AddField(
            model_name='conformancechecking',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask'),
        ),
    ]
