# Generated by Django 3.2.9 on 2022-04-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stakeholder_stakeholderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='StakeholderListDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stakeholderlist')),
                ('stakeholder_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stakeholder')),
            ],
        ),
    ]
