# Generated by Django 3.2.9 on 2022-04-28 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stakeholderlistdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='conformancechecking',
            name='stakeholder_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.stakeholderlist'),
            preserve_default=False,
        ),
    ]
