# Generated by Django 3.2.9 on 2022-04-28 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_conformancechecking_stakeholder_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConformanceCheckingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.TimeField()),
                ('status', models.CharField(max_length=20)),
                ('node', models.CharField(max_length=50)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conformancechecking')),
            ],
        ),
    ]
